name: Build + Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.git**'
      - 'service/**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: false
        default: 'latest'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup nodejs
        uses: actions/setup-node@main
        with:
          node-version: 'latest'

      - name: setup go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'

      - name: processing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # building and compressing
          git clone https://github.com/gek64/gobd
          go build -C gobd -o "../gobd_runner"
          chmod +x ./gobd_runner
          ./gobd_runner -main -d bin -no_debug -no_cgo
          ./gobd_runner -os linux -arch mipsle -n ${{ github.event.repository.name }}-softfloat -d bin -no_debug -no_cgo -envs 'GOMIPS=softfloat'

          # delete all releases and their tags
          gh release list | awk -F '\t' '{print $3}' | while read -r line; do gh release delete --yes --cleanup-tag "$line"; done

          # create release
          if [ "${{ inputs.version }}" != "" ]; then
            tag="${{ inputs.version }}"
          else
            tag="$(go run . -v)"
          fi
          gh release create "$tag" --generate-notes "bin/*"
